/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import db_objs.Logs;
import db_objs.MyJDBC;
import db_objs.User;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gilbert
 */
public class registered_frame extends javax.swing.JFrame {

    public static User user;

    /**
     * Creates new form login_frame
     */
    public static registered_frame registerFrame;

    public registered_frame(User user) {
        initComponents();
        registerFrame = this;

    }
    ImageIcon icon = new ImageIcon("C:\\Users\\gilbert\\Downloads\\aaaa.png");
    Image img = icon.getImage().getScaledInstance(40, 45, Image.SCALE_SMOOTH);
    ImageIcon i = new ImageIcon(img);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        username_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        repassword_field = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        cancel_button = new javax.swing.JButton();
        register_button = new javax.swing.JButton();
        loginButton = new javax.swing.JLabel();
        name_field1 = new javax.swing.JTextField();
        email_field1 = new javax.swing.JTextField();
        address_field1 = new javax.swing.JTextField();
        password_field1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(85, 68, 61));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(i);
        jLabel15.setText("<html> <head> <style> p.small {   line-height:-10; } </style> </head> <body>  <p class=\"small\"> <b>NATIONAL UNIVERSITY</b><p style=\"font-size: 12;\"> Education That Works | ig: saryu4u</p> </p>  </body>");
        jLabel15.setIconTextGap(15);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 68, 61));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html><body style=\"text-align:center;\">This is a project in Object Oriented Programming. A Inventory System integrated with MySQL database. <br> \nThis was developed by Laurence Ian using Apache NeatBeans and MySQL</body> </html>");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 245, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_field.setBackground(new java.awt.Color(248, 245, 242));
        username_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        username_field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "USERNAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(85, 68, 61))); // NOI18N
        username_field.setSelectedTextColor(new java.awt.Color(248, 245, 242));
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 430, 60));

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("show");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, -1, 30));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("show");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, 30));

        repassword_field.setBackground(new java.awt.Color(248, 245, 242));
        repassword_field.setEchoChar('•');
        repassword_field.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        repassword_field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "RE-TYPE PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(85, 68, 61))); // NOI18N
        repassword_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repassword_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(repassword_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 430, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 68, 61));
        jLabel2.setText("REGISTRATION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 340, 40));

        cancel_button.setBackground(new java.awt.Color(85, 68, 61));
        cancel_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_button.setText("CANCEL");
        cancel_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 430, 40));

        register_button.setBackground(new java.awt.Color(85, 68, 61));
        register_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        register_button.setForeground(new java.awt.Color(255, 255, 255));
        register_button.setText("REGISTER");
        register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 430, 40));

        loginButton.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 51, 255));
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButton.setText("<html><a href=\"#\">already have an account? click here</a></html>");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1000, 30));

        name_field1.setBackground(new java.awt.Color(248, 245, 242));
        name_field1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name_field1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(85, 68, 61))); // NOI18N
        name_field1.setSelectedTextColor(new java.awt.Color(248, 245, 242));
        name_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_field1ActionPerformed(evt);
            }
        });
        jPanel1.add(name_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 430, 60));

        email_field1.setBackground(new java.awt.Color(248, 245, 242));
        email_field1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email_field1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "EMAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(85, 68, 61))); // NOI18N
        email_field1.setSelectedTextColor(new java.awt.Color(248, 245, 242));
        email_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_field1ActionPerformed(evt);
            }
        });
        jPanel1.add(email_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 430, 60));

        address_field1.setBackground(new java.awt.Color(248, 245, 242));
        address_field1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        address_field1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(85, 68, 61))); // NOI18N
        address_field1.setSelectedTextColor(new java.awt.Color(248, 245, 242));
        address_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_field1ActionPerformed(evt);
            }
        });
        jPanel1.add(address_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 430, 60));

        password_field1.setBackground(new java.awt.Color(248, 245, 242));
        password_field1.setEchoChar('•');
        password_field1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        password_field1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PASSWORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(85, 68, 61))); // NOI18N
        password_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_field1ActionPerformed(evt);
            }
        });
        jPanel1.add(password_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 430, 60));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(85, 68, 61));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(i);
        jLabel16.setText("<html> <head> <style> p.small {   line-height:-10; } </style> </head> <body>  <p class=\"small\"> <b>NATIONAL UNIVERSITY</b><p style=\"font-size: 12;\"> Education That Works | ig: saryu4u</p> </p>  </body>");
        jLabel16.setIconTextGap(15);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 310, 80));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 68, 61));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html><body style=\"text-align:center;\">Sponsored By <br>Coca-Cola </body> </html>");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 280, 60));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 68, 61));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html><body style=\"text-align:center;\">Sponsored By <br>Lola Remedios</body> </html>");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 280, 60));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(85, 68, 61));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<html><body style=\"text-align:center;\">Powered By <br>Cobra Energy Drink</body> </html>");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 280, 60));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(85, 68, 61));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("<html><body style=\"text-align:center;\">Sponsored By <br> IKEA</body> </html>");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 280, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new login_frame(user).setVisible(true);
    }//GEN-LAST:event_loginButtonMouseClicked

    private void name_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_field1ActionPerformed

    private void email_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_field1ActionPerformed

    private void address_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_field1ActionPerformed

    private void repassword_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repassword_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repassword_fieldActionPerformed

    private void password_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_field1ActionPerformed
    Logs logs;
    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO a dd your handling code here:

        String username = username_field.getText();
        String name = name_field1.getText();
        String address = address_field1.getText();
        String email = email_field1.getText();
        String password = String.valueOf(password_field1.getPassword());
        String rePassword = String.valueOf(repassword_field.getPassword());
        String status = "not verified";

        if (username.isEmpty() && name.isEmpty() && address.isEmpty() && email.isEmpty() && password.isEmpty() && rePassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the information to register", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Username", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Name", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Address", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Password", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (rePassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please re-enter your Password", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!password.equals(rePassword)) {
                JOptionPane.showMessageDialog(this, "Please make sure to to match your Password", "WARNING", JOptionPane.ERROR_MESSAGE);
            } else if (!email.contains("@gmail.com")) {
                JOptionPane.showMessageDialog(this, "Please make sure to input a VALID EMAIL", "WARNING", JOptionPane.ERROR_MESSAGE);
            } else if (username.length() < 6) {
                JOptionPane.showMessageDialog(this, "The Username must be ATLEAST 6 Characters", "WARNING", JOptionPane.ERROR_MESSAGE);
            } else if (password.equals(rePassword) && password.length() < 6) {
                JOptionPane.showMessageDialog(this, "The Password must be ATLEAST 6 Characters", "WARNING", JOptionPane.ERROR_MESSAGE);
            } else if (MyJDBC.checkUser(username)) {
                JOptionPane.showMessageDialog(this, "The Username is already Existed", "WARNING", JOptionPane.ERROR_MESSAGE);
            } else {
                if (MyJDBC.register(username, password, name, address, email, status)) {
                    JOptionPane.showMessageDialog(this, "Register Successfully");
//                    logs = new Logs(0, "CREATED AN ACCOUNT" , name ,null,null);
//                    MyJDBC.addLogsToDatabase(logs);
                    this.dispose();
                    new login_frame(user).setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_register_buttonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:

        if (jLabel8.getText().equals("show")) {
            password_field1.setEchoChar((char) 0); // Show password
            jLabel8.setText("hide");
            password_field1.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        } else {
            password_field1.setEchoChar('•'); // Hide password
            password_field1.setFont(new Font("Segoe UI", Font.PLAIN, 26));
            jLabel8.setText("show");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (jLabel9.getText().equals("show")) {
            repassword_field.setEchoChar((char) 0); // Show password
            repassword_field.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            jLabel9.setText("hide");
        } else {
            repassword_field.setEchoChar('•'); // Hide password
            repassword_field.setFont(new Font("Segoe UI", Font.PLAIN, 25));
            jLabel9.setText("show");
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login_frame(user).setVisible(true);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_field1;
    private javax.swing.JButton cancel_button;
    private javax.swing.JTextField email_field1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginButton;
    private javax.swing.JTextField name_field1;
    private javax.swing.JPasswordField password_field1;
    private javax.swing.JButton register_button;
    private javax.swing.JPasswordField repassword_field;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
